### ISSUE TITLE
not sync time

### ISSUE THREAD

**Issue by panshengjie** [rascol/PPS-Client#1]
hello!

when I first run pps-clinet , It prints 
`2021-05-28 12:15:12.000000  20  jitter:  0   freqOffset:  0.000000  avgCorrection:  0.000000  clamp: 32768*`

some time past, it goes
`2021-05-28 15:13:50.000000  10738  jitter:  0   freqOffset:  0.000000  avgCorrection:  0.000000  clamp: 1`

so I thought time synchonized. But then I changed sys time with wrong time(for test) , however it did't detect/correct it, something is wrong

I've tried restart/reboot/reinstall, change time in milliseconds, and some . Nothing changes,  still print
`2021-05-28 17:00:31.000000  18582  jitter:  0   freqOffset:  0.000000  avgCorrection:  0.000000  clamp: 1`

it seems a data/cache is saved somewhere in disk (because num keep counting on), and I can't find it, even pps-client-remove -a

**Comment by panshengjie** [comment]
ppstest show this
`source 0 - assert 0.000000000, sequence: 0 - clear  1622194401.261356935, sequence: 2355`

**Comment by rascol** [comment]
This is exactly what happens when no PPS signal is present. This is not a problem with PPS-Client. It's a problem with electrical connection or connection software.

**Comment by rascol** [comment]
Closing this issue.
